name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - uses: subosito/flutter-action@v1
      - name: Setup Firebase
        run: |
          curl -sL https://firebase.tools | bash
          dart pub global activate flutterfire_cli
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_FILE_BASE64 }}" | base64 -d > gcloud-service-key.json
          GOOGLE_APPLICATION_CREDENTIALS=gcloud-service-key.json \
          flutterfire configure \
          --project save-the-potato  \
          --android-app-id=dev.app2pack.savethepotato \
          --ios-bundle-id=dev.app2pack.savethepotato \
          --platforms=android,ios \
          > /dev/null 2>&1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit