name: Zip and Send Secrets to Telegram

on:
  push:

jobs:
  zip-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare and Zip Files with Password
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON_FILE_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_FILE_BASE64 }}
          ANDROID_GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.ANDROID_GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON_FILE_BASE64 }}" | base64 --decode > google_credentials.json
          echo "${{ secrets.ANDROID_GOOGLE_SERVICE_ACCOUNT_JSON }}" > android_service_account.json
          zip -P neo123 secrets.zip google_credentials.json android_service_account.json

      - name: Send ZIP File to Telegram
        env:
          TELEGRAM_BOT_API_TOKEN: ${{ secrets.TTG_TELEGRAM_BOT_API_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TTG_TELEGRAM_RELEASE_CHANNEL_ID }}
        run: |
          curl -F chat_id="${TELEGRAM_CHANNEL_ID}" \
               -F document=@secrets.zip \
               https://api.telegram.org/bot${TELEGRAM_BOT_API_TOKEN}/sendDocument